version: '3'

services:
  gribapi:
    container_name: paint-gribapi
    build:
      context: ./dockerfiles/gribapi
    volumes:
      - C:/Users/golov/IdeaProjects/paint/client/public:/gribapi/public
      - C:/paint/gribapi/logs:/gribapi/logs
      - ./gribapi:/gribapi
    restart: always
    environment:
      - PARAMS=${PARAMS}
